/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Roboto Flex',
          'Roboto',
          'Inter',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        display: [
          'Google Sans',
          'Google Sans Flex',
          'Inter',
          'Roboto Flex',
          'sans-serif',
        ],
      },
      colors: {
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        // Material 3 system colors (token alias — CSS vars in index.css)
        primary: 'rgb(var(--sys-primary) / <alpha-value>)',
        onPrimary: 'rgb(var(--sys-on-primary) / <alpha-value>)',
        primaryContainer: 'rgb(var(--sys-primary-container) / <alpha-value>)',
        onPrimaryContainer: 'rgb(var(--sys-on-primary-container) / <alpha-value>)',
        secondary: 'rgb(var(--sys-secondary) / <alpha-value>)',
        secondaryContainer: 'rgb(var(--sys-secondary-container) / <alpha-value>)',
        onSecondaryContainer: 'rgb(var(--sys-on-secondary-container) / <alpha-value>)',
        tertiary: 'rgb(var(--sys-tertiary) / <alpha-value>)',
        tertiaryContainer: 'rgb(var(--sys-tertiary-container) / <alpha-value>)',
        error: 'rgb(var(--sys-error) / <alpha-value>)',
        errorContainer: 'rgb(var(--sys-error-container) / <alpha-value>)',
        surfaceContainerLowest: 'rgb(var(--sys-surface-container-lowest) / <alpha-value>)',
        surfaceContainerLow: 'rgb(var(--sys-surface-container-low) / <alpha-value>)',
        surfaceContainer: 'rgb(var(--sys-surface-container) / <alpha-value>)',
        surfaceContainerHigh: 'rgb(var(--sys-surface-container-high) / <alpha-value>)',
        surfaceContainerHighest: 'rgb(var(--sys-surface-container-highest) / <alpha-value>)',
        outline: 'rgb(var(--sys-outline) / <alpha-value>)',
        outlineVariant: 'rgb(var(--sys-outline-variant) / <alpha-value>)',
        inverseSurface: 'rgb(var(--sys-inverse-surface) / <alpha-value>)',
        inverseOnSurface: 'rgb(var(--sys-inverse-on-surface) / <alpha-value>)',
        scrim: 'rgb(var(--sys-scrim) / <alpha-value>)',
        // Legacy aliases (keep for migration)
        bg: 'rgb(var(--bg) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--surface-3) / <alpha-value>)',
        'surface-muted': 'rgb(var(--surface-muted) / <alpha-value>)',
        elevated: 'rgb(var(--surface-elevated) / <alpha-value>)',
        card: 'rgb(var(--surface-elevated) / <alpha-value>)',
        ink: {
          DEFAULT: 'rgb(var(--ink) / <alpha-value>)',
          secondary: 'rgb(var(--ink-secondary) / <alpha-value>)',
          muted: 'rgb(var(--ink-muted) / <alpha-value>)',
        },
        line: 'rgb(var(--line) / <alpha-value>)',
        'border-subtle': 'rgb(var(--border-subtle) / <alpha-value>)',
        'border-strong': 'rgb(var(--border-strong) / <alpha-value>)',
        accent: {
          DEFAULT: 'rgb(var(--accent) / <alpha-value>)',
          hover: 'rgb(var(--accent-hover) / <alpha-value>)',
          soft: 'rgb(var(--accent-soft) / <alpha-value>)',
          ink: 'rgb(var(--accent-ink) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--success) / <alpha-value>)',
          soft: 'rgb(var(--success-soft) / <alpha-value>)',
        },
        warning: {
          DEFAULT: 'rgb(var(--warning) / <alpha-value>)',
          soft: 'rgb(var(--warning-soft) / <alpha-value>)',
        },
        danger: {
          DEFAULT: 'rgb(var(--danger) / <alpha-value>)',
          soft: 'rgb(var(--danger-soft) / <alpha-value>)',
        },
        info: {
          DEFAULT: 'rgb(var(--info) / <alpha-value>)',
          soft: 'rgb(var(--info-soft) / <alpha-value>)',
        },
      },
      borderRadius: {
        none: '0',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '28px',
        full: '9999px',
      },
      boxShadow: {
        card: '0 1px 2px rgb(15 23 42 / 0.05), 0 1px 3px rgb(15 23 42 / 0.08)',
        'card-hover': '0 2px 4px rgb(15 23 42 / 0.06), 0 4px 12px rgb(15 23 42 / 0.08)',
        modal: '0 10px 30px rgb(15 23 42 / 0.18), 0 4px 10px rgb(15 23 42 / 0.12)',
        elevation1: '0 1px 2px rgb(0 0 0 / 0.12), 0 1px 3px rgb(0 0 0 / 0.08)',
        elevation2: '0 2px 6px rgb(0 0 0 / 0.12), 0 4px 12px rgb(0 0 0 / 0.08)',
        elevation3: '0 4px 8px rgb(0 0 0 / 0.14), 0 6px 12px rgb(0 0 0 / 0.10)',
        fab: '0 4px 12px rgb(0 0 0 / 0.15), 0 8px 24px rgb(0 0 0 / 0.12), 0 1px 3px rgb(0 0 0 / 0.08)',
        'fab-hover': '0 6px 16px rgb(0 0 0 / 0.18), 0 12px 32px rgb(0 0 0 / 0.14)',
      },
    },
  },
  plugins: [],
};